services:
    client:
        container_name: lipsql_container
        build:
            context: .
        ports:
            - '3004:3000'
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        networks:
            - lipsql_network

networks:
    lipsql_network:
        driver: bridge
